version: '2'

volumes:
  tec_snslogin_svr_syncs:
    external: true

services:

  nginx:
    image: nginx
    container_name: "snslogin-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./svr:/svr
      - tec_snslogin_svr_syncs:/svr
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Ssl/snslogin_dev_cde.crt.pem:/etc/nginx/conf.d/snslogin_dev_cde.cert.pem
      - ./Ssl/snslogin_dev_cde.key.pem:/etc/nginx/conf.d/snslogin_dev_cde.key.pem
      - ./weblog:/var/log/nginx
    depends_on:
      - phpfpm

  phpfpm:
    build: ./phpfpm
    container_name: "snslogin-php"
    volumes:
#      - ./svr:/svr
#      - ./applog:/svr/app/storage/logs
       - tec_snslogin_svr_syncs:/svr
       - ./phpfpm/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - pgsql
      - redis

  pgsql:
    restart: always
    image: postgres:11-alpine
    container_name: "snslogin-postgres"
    environment:
      POSTGRES_USER: pgusr
      POSTGRES_PASSWORD: pgpwd
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: "snslogin-redis"

  adminer:
    image: adminer:4.6
    container_name: "snslogin-adminer"
    ports:
      - "8090:8080"
    depends_on:
      - pgsql
